language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  app: iot-webui
  api_key:
    secure: Ubd7HE2Y3HTSyu1hCIKVTOxQLFSU75OJ4+ewkaWiPHC4o6vw58gJSxvLtdKf1RTr1zf9aI6jt+4dceCjejrHadarMueCbnApA1R9rNSlQOoTsk+49EGOz9CypwsvfbixpBWe4vJyCZKr1Ek2wGsxkcAMG5eJViKnX+AdBpqTLuJphzkzqbVAWFFdKiHhZOsZgW7ZZowVJbFcWSW24OU4+yw84bvR1C5iVSFDM4GAV9Fj8iRlJUCwCqheQ3a8vxVbbP42z4DNSXACQB8gDaAVWL3WfPwy+Ziq2ezWHCTIpmofogD7zTYcxIUMhN9kvYjtgavEDVh+34cmMUQJ7UdZmpDm0cvWCjqNejX9fH4I8YBXhtXFPvQKUy83Ml7pSUeHutIVrcesgKlDDdbx1OUsPH5cLljx8vmUpH+10FuAX+9mqkv62yG6Ng8VuY6wX8NWRJ7GNKkHLT21xH2NW2zsTnq9jlhZa0M3sL5uCTPDGlszLLQApaxtKRRJ222WB+i0oWljqDRD3YFjyDAxz52W2J5uS7QudFxDhrms/SL9rl5momlrcKNkdr7O7+HQuz/I3CMtfeWDTC1Y+lfHtryL/+5UnkdkCWHGgncJAoBUgN133r5NvBTTj08Klnf8jf0+Xn8DAZliQBPBzWGgnNOgLm454+SjjXMxVvCXLClBKgo=
